### ISSUE TITLE
Mac/Linux version broken

### ISSUE THREAD

**Issue by SophieHou** [NCAR/NMDEdit#13]
Per NCAR Library user feedback on 20170502: "when trying to execute the NMDEdit apply_ncar_updates.sh, which simply output the following (approx) message and quit: "warning: updates to files are not complete". 

The user tried the installation a couple of times following the instructions posted on DASH: https://www2.cisl.ucar.edu/dash/search-and-discovery/NMDEdit

**Comment by dwstott** [comment]
Yes, this is expected behavior until the files are all updated to version 2 and working correctly for every operating system.
