### ISSUE TITLE
Match minimum required elements in NMDEdit to NCAR Dialect spreadsheet

### ISSUE THREAD

**Issue by dwstott** [NCAR/NMDEdit#2]
Update the NMDEdit code as needed to have the same minimum fields as indicated by NCAR Dialect spreadsheet at https://docs.google.com/spreadsheets/d/1PG0wt_HFLU_BUFFqlTBJeTu4_Dj2GByU00YoooR6O0M/edit#gid=0

**Comment by SophieHou** [comment]
After re-installing NMDEdit on a Windows laptop, NMDEdit is no longer start as a result.

Specifically, after the basic CatMDEdit was installed and the basic CatMDEdit was updated using the files from GitHub (date: 20170425), double clicking on the NMDEdit batch file did not start the NMDEdit as it had before. Double-clicking on the CatMDEdit batch file allowed the program to start, but new files could only be created but not edited using NCAR dialect.

**Comment by dwstott** [comment]
NMDEdit files were in process of being updated when retrieved for install. The name of the main jar file now is nmdedit-5.2.0.jar. That change involved the starup scripts and the apply_ncar_update scripts, too. Getting to point where perhaps we can lock it down for a while.
